package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderClientConfig(t *testing.T) {
	dir := t.TempDir()
	templatePath := filepath.Join(dir, "user.conf.template")
	template := "# generated by template\n  # local note\n\npriv=$CLIENT_PRIVATE_KEY\n\nip=$CLIENT_VPN_IP\nserver=$SERVER_PUBLIC_KEY\n"
	if err := os.WriteFile(templatePath, []byte(template), 0600); err != nil {
		t.Fatalf("write template: %v", err)
	}

	got, err := renderClientConfig(templatePath, "PRIV", "10.8.0.20", "SERVER")
	if err != nil {
		t.Fatalf("renderClientConfig: %v", err)
	}
	want := "priv=PRIV\n\nip=10.8.0.20\nserver=SERVER\n"
	if got != want {
		t.Errorf("rendered config = %q, want %q", got, want)
	}
}

func TestRenderClientConfigMissingTemplate(t *testing.T) {
	_, err := renderClientConfig(filepath.Join(t.TempDir(), "missing.template"), "PRIV", "10.8.0.20", "SERVER")
	if err == nil || !strings.Contains(err.Error(), "read user.conf.template") {
		t.Fatalf("error = %v, want template read error", err)
	}
}

func TestWriteClientConfigNoOverwrite(t *testing.T) {
	path := filepath.Join(t.TempDir(), "alice.vpn.conf")
	if err := writeClientConfigNoOverwrite(path, "first"); err != nil {
		t.Fatalf("writeClientConfigNoOverwrite first write: %v", err)
	}
	if err := writeClientConfigNoOverwrite(path, "second"); err == nil {
		t.Fatal("second write should fail")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read client config: %v", err)
	}
	if string(data) != "first" {
		t.Errorf("client config content = %q, want first", string(data))
	}
}
